package com.harry.wallet365.app_final;

/**
 * Created by Harry on 2019/1/9.
 * 处理RxJava切断管道方法
 * 命名方法 - 类名+方法名
 */
public enum DisposableFinal {

    LOGIN_ACTIVITY_SHOP_LOGIN,
    LOGIN_ACTIVITY_CUSTOMER_LOGIN,
    REGISTER_ACTIVITY_GET_VERIFICATION_CODE,
    REGISTER_ACTIVITY_REGISTER,
    FORGET_PASSWORD_ACTIVITY_FORGET_PASSWORD,
    FORGET_PASSWORD_ACTIVITY_GET_VERIFICATION_CODE,
}
