package com.harry.wallet365.app_final;

/**
 * Created by Harry on 2019/1/9.
 * 处理RxJava切断管道方法
 * 命名方法 - 类名+方法名
 */
public enum DisposableFinal {

    LOGIN_ACTIVITY_SHOP_LOGIN,
    LOGIN_ACTIVITY_CUSTOMER_LOGIN,
    REGISTER_ACTIVITY_GET_VERIFICATION_CODE,
    REGISTER_ACTIVITY_REGISTER,
    FORGET_PASSWORD_ACTIVITY_FORGET_PASSWORD,
    FORGET_PASSWORD_ACTIVITY_GET_VERIFICATION_CODE,
    HOME_FRAGMENT_GET_BANNER,
    HOME_FRAGMENT_GET_BOTTOM_LIST,
    HOME_FRAGMENT_GET_COUPON,
    HOME_FRAGMENT_USE_COUPON,
    SHOP_DETAIL_ACTIVITY_GET_SHOP_DETAIL,
    SHOP_DETAIL_ACTIVITY_GET_COUPON,
    GOODS_LIST_FRAGMENT_GET_GOODS_LIST,
    GOODS_DETAIL_ACTIVITY_GET_GOODS_DETAIL,
    USER_COMMENT_FRAGMENT_GET_COMMENT_LIST,
    NEARBY_FRAGMENT_GET_BANNER,
    NEARBY_FRAGMENT_GET_CATEGORY,
    NEARBY_FRAGMENT_GET_SHOP_LIST,
    SEARCH_SHOP_ACTIVITY_GET_SHOP_LIST,

}
